{% set name = "petlx" %}
{% set version = "1.0.3" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "68b90657a3385c4feb17d55ee0cac4e08ec3f2f968a3547cf926e6e6ff1645e1" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: 'python setup.py install '

requirements:
  host:
    - python
    - petl >=1.0
  run:
    - python
    - petl >=1.0

test:
  imports:
    - petlx
    - petlx.bio
    - petlx.test
    - petlx.test.bio

about:
  home: https://github.com/alimanfoo/petlx
  license: MIT License
  license_family: MIT
  license_file: ''
  summary: Optional extensions for the petl package.
  description: "petlx - Extensions to the petl package\n======================================\n\n``petlx`` is a collection of domain-specific and/or experimental extensions to \n`petl <https://github.com/alimanfoo/petl>`_,\
    \ a Python package for extracting,\ntransforming and loading tables of data.\n\n- Docs: http://petlx.readthedocs.org/\n- Source: https://github.com/alimanfoo/petlx\n- Download: http://pypi.python.org/pypi/petlx\n\
      - Mailing list: http://groups.google.com/group/python-etl"
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
